### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by fdncred** [nushell/vscode-nushell-lang#2]
- [x] add all keywords - duh
- [x] fix `[$variable` syntax highlighting
- [x] determine if we want to try to stay real close to nushell colors for syntax highlighting
- [ ] clean up code - there are a few extra files that aren't used in packaging but were/are useful to look at colors and such
- [x] document basic process to build the extension - more than just `vsce package`
- [x] register with microsoft [somewhere ](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) to publish to where ever extensions are hosted
- [x] change `set` to `let`
- [x] add screenshot to readme
- [x] foo-bar highlights `-b` by mistake
- [x] fix the `my-ls` bug
- [x] add a ci pipeline
- [x] add a release pipeline
- [x] change release pipeline to dynamically add a release number
- [x] vscode thinks \ is an escape character - fix that
- [x] put icon in extension
- [x] highlight units like `500ms`, the `ms` part.
- [x] do we really need a "light" theme?
- [x] add `...rest`
- [ ] ?

**Comment by fdncred** [comment]
Close enough. I'm closing this at 0.1.2 version. Feel free to submit more.
